const users = [
  {
    id: 1,
    name: 'SatVeer Singh',
    profileImage: '/images/01.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 2,
    name: 'Gurpreet Kour',
    profileImage: '/images/02.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 3,
    name: 'Pawan Kumar',
    profileImage: '/images/03.jpg',
  },
  {
    id: 4,
    name: 'SatVeer Singh',
    profileImage: '/images/04.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 5,
    name: 'Sukhdev Singh',
    profileImage: '/images/05.jpg',
  },
  {
    id: 6,
    name: 'SatVeer Singh',
    profileImage: '/images/05.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 7,
    name: 'SatVeer Singh',
    profileImage: '/images/06.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 8,
    name: 'SatVeer Singh',
    profileImage: '/images/07.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 9,
    name: 'SatVeer Singh',
    profileImage: '/images/07.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 10,
    name: 'SatVeer Singh',
    profileImage: '/images/07.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 11,
    name: 'SatVeer Singh',
    profileImage: '/images/07.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
  {
    id: 12,
    name: 'SatVeer Singh',
    profileImage: '/images/07.jpg',
    lastMessage: 'how are you?',
    lastMessageTime: '8:22 PM',
    numberOfUnreadMessages: 303,
  },
];

export default users;
